/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lichao_ffmpetyuv_MyPlay */

#ifndef _Included_com_lichao_ffmpetyuv_MyPlay
#define _Included_com_lichao_ffmpetyuv_MyPlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lichao_ffmpetyuv_MyPlay
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lichao_ffmpetyuv_MyPlay_render
  (JNIEnv *, jobject, jstring, jobject);

JNIEXPORT void JNICALL Java_com_lichao_ffmpetyuv_MyPlay_sound
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
